###########################################################################
#                  test Makefile
#                  Copyright (C) 2016  Van Chan Ngo
#
#
###########################################################################

OCAMLMAKEFILE = ../OCamlMakefile

SOURCES = 	liststack.ml \
			test.ml 

RESULT = test

# libs
LIBS = str unix

# includes
#LIBDIRS = lib/thelib

YFLAGS = -v

all: native-code

-include $(OCAMLMAKEFILE)
